### ISSUE TITLE
Agree structure of `config.yaml`

### ISSUE THREAD

**Issue by JamesSample** [SeaBee-no/documentation#32]
The fields/attributes of `config.yaml` should be discussed and agreed upon (e.g. which fields are mandatory and which are optional). We also need to choose a set of default values for optional parameters.

For the seabird missions flown during spring 2023 we have the following:

``` yaml
nfiles: 765 
collectedby: NINA (Sindre Molværsmyr)
```

As a next step, I suggest we extend this as follows:

``` yaml
nfiles: 765                            # Total number of files in the 'images' folder
collectedby: NINA (Sindre Molværsmyr)  # Organisation (pilot name)
mosaic: true                           # Whether to mosiac the raw images using ODM (true or false)
publish: true                          # Whether to publish the orthophoto to GeoNode (true or false)
```

to cover cases where pilots upload orthophotos that have already been generated by e.g. Pix4D.

Other attributes can be added over time - suggestions welcome!

**Comment by JamesSample** [comment]
For example, when `mosaic` is `true`, we could also allow users to specify ODM options such as `pc_quality` and `feature_quality` in this file.

**Comment by knl88** [comment]
It could also be nice with a couple more attributes, and perhaps split collectedby(not to important though)? for example

```yaml
title:                                             # could be nice
project:                                           # 
nfiles: 765                                        # Total number of files in the 'images' folder
institution:  NINA                                 # Organisation
creator_name: Sindre Molværsmyr                    # data collector
mosaic: true                                       # Whether to mosiac the raw images using ODM (true or false)
publish: true                                      # Whether to publish the orthophoto to GeoNode (true or false)
```

a `summary` attribute would also be nice, but perhaps not that practical. The suggested attributes are mostly to make the iso generation easier. Some of these fields can also be modified  from geonode, so it is mostly a question about what is most practical. 

PS: I took the attributes from [here](https://thredds.niva.no/thredds/uddc/datasets/msource-outlet.nc?catalog=file:/usr/local/tomcat/content/thredds/subcatalogs/loggers.xml&dataset=4b123377-e0a6-4c7e-b466-2f8a3199bc86)

PSS: Don't understand how @JamesSample managed to align the comments so well :)
